version: '3.8'
services:
  web:
    image: tsspredator_web:latest
    platform: linux/x86_64
    build:
      context: .
      dockerfile: webapp/Dockerfile
    working_dir: /app/server_tsspredator
    command: gunicorn --workers 6 --timeout 500 --graceful-timeout 500  --bind 0.0.0.0:5001 server_tsspredator.wsgi:tsspredator
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
    ports:
      - "${PORT_OUTPUT}:5001"
    volumes:
      - type: bind
        source: ${DATA_PREDATOR_PATH}
        target: /data
      - tmpDataPredator:/tmpData
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - type: bind
        source: ${REDIS_DATA_PATH}
        target: /data
    command: redis-server /data/redis.config
    

  celery:
    image: tsspredator_celery_app:latest
    platform: linux/x86_64
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery -A server_tsspredator.celery_app worker -B --loglevel=warning
    volumes:
      - tmpDataPredator:/tmpData
    depends_on:
      - redis

volumes:
  tmpDataPredator:
  



